/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CanvasIndexRouteImport } from './routes/canvas.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as DemoAgentSummaryRouteImport } from './routes/demo/agent-summary'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas.$canvasId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiContextItemsRouteImport } from './routes/api/context-items'
import { Route as ApiChatThreadsRouteImport } from './routes/api/chat-threads'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat-messages'
import { Route as ApiCanvasRouteImport } from './routes/api/canvas'
import { Route as ApiBlocksRouteImport } from './routes/api/blocks'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiZergCommitSummariesRouteImport } from './routes/api/zerg/commit-summaries'
import { Route as ApiScrapeContextRouteImport } from './routes/api/scrape/context'
import { Route as ApiPolarWebhooksRouteImport } from './routes/api/polar/webhooks'
import { Route as ApiPolarRefillCheckoutRouteImport } from './routes/api/polar/refill-checkout'
import { Route as ApiPolarPortalRouteImport } from './routes/api/polar/portal'
import { Route as ApiPolarCheckoutRouteImport } from './routes/api/polar/checkout'
import { Route as ApiPolarBillingRouteImport } from './routes/api/polar/billing'
import { Route as ApiExternalZergRouteImport } from './routes/api/external/zerg'
import { Route as ApiExternalContextRouteImport } from './routes/api/external/context'
import { Route as ApiExplainRenderRouteImport } from './routes/api/explain/render'
import { Route as ApiDebugEnvRouteImport } from './routes/api/debug.env'
import { Route as ApiChatMutationsRouteImport } from './routes/api/chat/mutations'
import { Route as ApiChatGuestRouteImport } from './routes/api/chat/guest'
import { Route as ApiChatAiRouteImport } from './routes/api/chat/ai'
import { Route as ApiCanvasImagesRouteImport } from './routes/api/canvas.images'
import { Route as ApiCanvasCanvasIdRouteImport } from './routes/api/canvas.$canvasId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiCanvasImagesImageIdRouteImport } from './routes/api/canvas.images.$imageId'
import { Route as ApiCanvasImagesImageIdInpaintRouteImport } from './routes/api/canvas.images.$imageId.inpaint'
import { Route as ApiCanvasImagesImageIdGenerateRouteImport } from './routes/api/canvas.images.$imageId.generate'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const DemoAgentSummaryRoute = DemoAgentSummaryRouteImport.update({
  id: '/demo/agent-summary',
  path: '/demo/agent-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => CanvasRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextItemsRoute = ApiContextItemsRouteImport.update({
  id: '/api/context-items',
  path: '/api/context-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: '/api/chat-threads',
  path: '/api/chat-threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/api/chat-messages',
  path: '/api/chat-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasRoute = ApiCanvasRouteImport.update({
  id: '/api/canvas',
  path: '/api/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlocksRoute = ApiBlocksRouteImport.update({
  id: '/api/blocks',
  path: '/api/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZergCommitSummariesRoute = ApiZergCommitSummariesRouteImport.update({
  id: '/api/zerg/commit-summaries',
  path: '/api/zerg/commit-summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeContextRoute = ApiScrapeContextRouteImport.update({
  id: '/api/scrape/context',
  path: '/api/scrape/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhooksRoute = ApiPolarWebhooksRouteImport.update({
  id: '/api/polar/webhooks',
  path: '/api/polar/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarRefillCheckoutRoute = ApiPolarRefillCheckoutRouteImport.update({
  id: '/api/polar/refill-checkout',
  path: '/api/polar/refill-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarPortalRoute = ApiPolarPortalRouteImport.update({
  id: '/api/polar/portal',
  path: '/api/polar/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarCheckoutRoute = ApiPolarCheckoutRouteImport.update({
  id: '/api/polar/checkout',
  path: '/api/polar/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarBillingRoute = ApiPolarBillingRouteImport.update({
  id: '/api/polar/billing',
  path: '/api/polar/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalZergRoute = ApiExternalZergRouteImport.update({
  id: '/api/external/zerg',
  path: '/api/external/zerg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalContextRoute = ApiExternalContextRouteImport.update({
  id: '/api/external/context',
  path: '/api/external/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRenderRoute = ApiExplainRenderRouteImport.update({
  id: '/api/explain/render',
  path: '/api/explain/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugEnvRoute = ApiDebugEnvRouteImport.update({
  id: '/api/debug/env',
  path: '/api/debug/env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMutationsRoute = ApiChatMutationsRouteImport.update({
  id: '/api/chat/mutations',
  path: '/api/chat/mutations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGuestRoute = ApiChatGuestRouteImport.update({
  id: '/api/chat/guest',
  path: '/api/chat/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAiRoute = ApiChatAiRouteImport.update({
  id: '/api/chat/ai',
  path: '/api/chat/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasImagesRoute = ApiCanvasImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ApiCanvasRoute,
} as any)
const ApiCanvasCanvasIdRoute = ApiCanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => ApiCanvasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasImagesImageIdRoute = ApiCanvasImagesImageIdRouteImport.update({
  id: '/$imageId',
  path: '/$imageId',
  getParentRoute: () => ApiCanvasImagesRoute,
} as any)
const ApiCanvasImagesImageIdInpaintRoute =
  ApiCanvasImagesImageIdInpaintRouteImport.update({
    id: '/inpaint',
    path: '/inpaint',
    getParentRoute: () => ApiCanvasImagesImageIdRoute,
  } as any)
const ApiCanvasImagesImageIdGenerateRoute =
  ApiCanvasImagesImageIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiCanvasImagesImageIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocks': typeof BlocksRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/context-items': typeof ApiContextItemsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/users': typeof ApiUsersRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/demo/agent-summary': typeof DemoAgentSummaryRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/canvas/': typeof CanvasIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRoute
  '/api/canvas/images': typeof ApiCanvasImagesRouteWithChildren
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/guest': typeof ApiChatGuestRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/debug/env': typeof ApiDebugEnvRoute
  '/api/explain/render': typeof ApiExplainRenderRoute
  '/api/external/context': typeof ApiExternalContextRoute
  '/api/external/zerg': typeof ApiExternalZergRoute
  '/api/polar/billing': typeof ApiPolarBillingRoute
  '/api/polar/checkout': typeof ApiPolarCheckoutRoute
  '/api/polar/portal': typeof ApiPolarPortalRoute
  '/api/polar/refill-checkout': typeof ApiPolarRefillCheckoutRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/api/scrape/context': typeof ApiScrapeContextRoute
  '/api/zerg/commit-summaries': typeof ApiZergCommitSummariesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/canvas/images/$imageId': typeof ApiCanvasImagesImageIdRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/canvas/images/$imageId/generate': typeof ApiCanvasImagesImageIdGenerateRoute
  '/api/canvas/images/$imageId/inpaint': typeof ApiCanvasImagesImageIdInpaintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocks': typeof BlocksRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/users': typeof UsersRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/context-items': typeof ApiContextItemsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/users': typeof ApiUsersRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/demo/agent-summary': typeof DemoAgentSummaryRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/canvas': typeof CanvasIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRoute
  '/api/canvas/images': typeof ApiCanvasImagesRouteWithChildren
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/guest': typeof ApiChatGuestRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/debug/env': typeof ApiDebugEnvRoute
  '/api/explain/render': typeof ApiExplainRenderRoute
  '/api/external/context': typeof ApiExternalContextRoute
  '/api/external/zerg': typeof ApiExternalZergRoute
  '/api/polar/billing': typeof ApiPolarBillingRoute
  '/api/polar/checkout': typeof ApiPolarCheckoutRoute
  '/api/polar/portal': typeof ApiPolarPortalRoute
  '/api/polar/refill-checkout': typeof ApiPolarRefillCheckoutRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/api/scrape/context': typeof ApiScrapeContextRoute
  '/api/zerg/commit-summaries': typeof ApiZergCommitSummariesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/canvas/images/$imageId': typeof ApiCanvasImagesImageIdRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/canvas/images/$imageId/generate': typeof ApiCanvasImagesImageIdGenerateRoute
  '/api/canvas/images/$imageId/inpaint': typeof ApiCanvasImagesImageIdInpaintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocks': typeof BlocksRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/context-items': typeof ApiContextItemsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/users': typeof ApiUsersRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/demo/agent-summary': typeof DemoAgentSummaryRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/canvas/': typeof CanvasIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRoute
  '/api/canvas/images': typeof ApiCanvasImagesRouteWithChildren
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/guest': typeof ApiChatGuestRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/debug/env': typeof ApiDebugEnvRoute
  '/api/explain/render': typeof ApiExplainRenderRoute
  '/api/external/context': typeof ApiExternalContextRoute
  '/api/external/zerg': typeof ApiExternalZergRoute
  '/api/polar/billing': typeof ApiPolarBillingRoute
  '/api/polar/checkout': typeof ApiPolarCheckoutRoute
  '/api/polar/portal': typeof ApiPolarPortalRoute
  '/api/polar/refill-checkout': typeof ApiPolarRefillCheckoutRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/api/scrape/context': typeof ApiScrapeContextRoute
  '/api/zerg/commit-summaries': typeof ApiZergCommitSummariesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/canvas/images/$imageId': typeof ApiCanvasImagesImageIdRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/canvas/images/$imageId/generate': typeof ApiCanvasImagesImageIdGenerateRoute
  '/api/canvas/images/$imageId/inpaint': typeof ApiCanvasImagesImageIdInpaintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blocks'
    | '/canvas'
    | '/chat'
    | '/home'
    | '/login'
    | '/marketplace'
    | '/settings'
    | '/users'
    | '/api/blocks'
    | '/api/canvas'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/context-items'
    | '/api/health'
    | '/api/users'
    | '/canvas/$canvasId'
    | '/demo/agent-summary'
    | '/settings/billing'
    | '/settings/preferences'
    | '/settings/profile'
    | '/canvas/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/canvas/$canvasId'
    | '/api/canvas/images'
    | '/api/chat/ai'
    | '/api/chat/guest'
    | '/api/chat/mutations'
    | '/api/debug/env'
    | '/api/explain/render'
    | '/api/external/context'
    | '/api/external/zerg'
    | '/api/polar/billing'
    | '/api/polar/checkout'
    | '/api/polar/portal'
    | '/api/polar/refill-checkout'
    | '/api/polar/webhooks'
    | '/api/scrape/context'
    | '/api/zerg/commit-summaries'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/canvas/images/$imageId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/canvas/images/$imageId/generate'
    | '/api/canvas/images/$imageId/inpaint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blocks'
    | '/chat'
    | '/home'
    | '/login'
    | '/marketplace'
    | '/users'
    | '/api/blocks'
    | '/api/canvas'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/context-items'
    | '/api/health'
    | '/api/users'
    | '/canvas/$canvasId'
    | '/demo/agent-summary'
    | '/settings/billing'
    | '/settings/preferences'
    | '/settings/profile'
    | '/canvas'
    | '/settings'
    | '/api/auth/$'
    | '/api/canvas/$canvasId'
    | '/api/canvas/images'
    | '/api/chat/ai'
    | '/api/chat/guest'
    | '/api/chat/mutations'
    | '/api/debug/env'
    | '/api/explain/render'
    | '/api/external/context'
    | '/api/external/zerg'
    | '/api/polar/billing'
    | '/api/polar/checkout'
    | '/api/polar/portal'
    | '/api/polar/refill-checkout'
    | '/api/polar/webhooks'
    | '/api/scrape/context'
    | '/api/zerg/commit-summaries'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/canvas/images/$imageId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/canvas/images/$imageId/generate'
    | '/api/canvas/images/$imageId/inpaint'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/blocks'
    | '/canvas'
    | '/chat'
    | '/home'
    | '/login'
    | '/marketplace'
    | '/settings'
    | '/users'
    | '/api/blocks'
    | '/api/canvas'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/context-items'
    | '/api/health'
    | '/api/users'
    | '/canvas/$canvasId'
    | '/demo/agent-summary'
    | '/settings/billing'
    | '/settings/preferences'
    | '/settings/profile'
    | '/canvas/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/canvas/$canvasId'
    | '/api/canvas/images'
    | '/api/chat/ai'
    | '/api/chat/guest'
    | '/api/chat/mutations'
    | '/api/debug/env'
    | '/api/explain/render'
    | '/api/external/context'
    | '/api/external/zerg'
    | '/api/polar/billing'
    | '/api/polar/checkout'
    | '/api/polar/portal'
    | '/api/polar/refill-checkout'
    | '/api/polar/webhooks'
    | '/api/scrape/context'
    | '/api/zerg/commit-summaries'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/canvas/images/$imageId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/canvas/images/$imageId/generate'
    | '/api/canvas/images/$imageId/inpaint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BlocksRoute: typeof BlocksRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsersRoute: typeof UsersRoute
  ApiBlocksRoute: typeof ApiBlocksRoute
  ApiCanvasRoute: typeof ApiCanvasRouteWithChildren
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRoute
  ApiContextItemsRoute: typeof ApiContextItemsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUsersRoute: typeof ApiUsersRoute
  DemoAgentSummaryRoute: typeof DemoAgentSummaryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatAiRoute: typeof ApiChatAiRoute
  ApiChatGuestRoute: typeof ApiChatGuestRoute
  ApiChatMutationsRoute: typeof ApiChatMutationsRoute
  ApiDebugEnvRoute: typeof ApiDebugEnvRoute
  ApiExplainRenderRoute: typeof ApiExplainRenderRoute
  ApiExternalContextRoute: typeof ApiExternalContextRoute
  ApiExternalZergRoute: typeof ApiExternalZergRoute
  ApiPolarBillingRoute: typeof ApiPolarBillingRoute
  ApiPolarCheckoutRoute: typeof ApiPolarCheckoutRoute
  ApiPolarPortalRoute: typeof ApiPolarPortalRoute
  ApiPolarRefillCheckoutRoute: typeof ApiPolarRefillCheckoutRoute
  ApiPolarWebhooksRoute: typeof ApiPolarWebhooksRoute
  ApiScrapeContextRoute: typeof ApiScrapeContextRoute
  ApiZergCommitSummariesRoute: typeof ApiZergCommitSummariesRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/demo/agent-summary': {
      id: '/demo/agent-summary'
      path: '/demo/agent-summary'
      fullPath: '/demo/agent-summary'
      preLoaderRoute: typeof DemoAgentSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-items': {
      id: '/api/context-items'
      path: '/api/context-items'
      fullPath: '/api/context-items'
      preLoaderRoute: typeof ApiContextItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-threads': {
      id: '/api/chat-threads'
      path: '/api/chat-threads'
      fullPath: '/api/chat-threads'
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-messages': {
      id: '/api/chat-messages'
      path: '/api/chat-messages'
      fullPath: '/api/chat-messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas': {
      id: '/api/canvas'
      path: '/api/canvas'
      fullPath: '/api/canvas'
      preLoaderRoute: typeof ApiCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blocks': {
      id: '/api/blocks'
      path: '/api/blocks'
      fullPath: '/api/blocks'
      preLoaderRoute: typeof ApiBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zerg/commit-summaries': {
      id: '/api/zerg/commit-summaries'
      path: '/api/zerg/commit-summaries'
      fullPath: '/api/zerg/commit-summaries'
      preLoaderRoute: typeof ApiZergCommitSummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/context': {
      id: '/api/scrape/context'
      path: '/api/scrape/context'
      fullPath: '/api/scrape/context'
      preLoaderRoute: typeof ApiScrapeContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhooks': {
      id: '/api/polar/webhooks'
      path: '/api/polar/webhooks'
      fullPath: '/api/polar/webhooks'
      preLoaderRoute: typeof ApiPolarWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/refill-checkout': {
      id: '/api/polar/refill-checkout'
      path: '/api/polar/refill-checkout'
      fullPath: '/api/polar/refill-checkout'
      preLoaderRoute: typeof ApiPolarRefillCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/portal': {
      id: '/api/polar/portal'
      path: '/api/polar/portal'
      fullPath: '/api/polar/portal'
      preLoaderRoute: typeof ApiPolarPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/checkout': {
      id: '/api/polar/checkout'
      path: '/api/polar/checkout'
      fullPath: '/api/polar/checkout'
      preLoaderRoute: typeof ApiPolarCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/billing': {
      id: '/api/polar/billing'
      path: '/api/polar/billing'
      fullPath: '/api/polar/billing'
      preLoaderRoute: typeof ApiPolarBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/zerg': {
      id: '/api/external/zerg'
      path: '/api/external/zerg'
      fullPath: '/api/external/zerg'
      preLoaderRoute: typeof ApiExternalZergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/context': {
      id: '/api/external/context'
      path: '/api/external/context'
      fullPath: '/api/external/context'
      preLoaderRoute: typeof ApiExternalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain/render': {
      id: '/api/explain/render'
      path: '/api/explain/render'
      fullPath: '/api/explain/render'
      preLoaderRoute: typeof ApiExplainRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/env': {
      id: '/api/debug/env'
      path: '/api/debug/env'
      fullPath: '/api/debug/env'
      preLoaderRoute: typeof ApiDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/mutations': {
      id: '/api/chat/mutations'
      path: '/api/chat/mutations'
      fullPath: '/api/chat/mutations'
      preLoaderRoute: typeof ApiChatMutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/guest': {
      id: '/api/chat/guest'
      path: '/api/chat/guest'
      fullPath: '/api/chat/guest'
      preLoaderRoute: typeof ApiChatGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/ai': {
      id: '/api/chat/ai'
      path: '/api/chat/ai'
      fullPath: '/api/chat/ai'
      preLoaderRoute: typeof ApiChatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/images': {
      id: '/api/canvas/images'
      path: '/images'
      fullPath: '/api/canvas/images'
      preLoaderRoute: typeof ApiCanvasImagesRouteImport
      parentRoute: typeof ApiCanvasRoute
    }
    '/api/canvas/$canvasId': {
      id: '/api/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/api/canvas/$canvasId'
      preLoaderRoute: typeof ApiCanvasCanvasIdRouteImport
      parentRoute: typeof ApiCanvasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/images/$imageId': {
      id: '/api/canvas/images/$imageId'
      path: '/$imageId'
      fullPath: '/api/canvas/images/$imageId'
      preLoaderRoute: typeof ApiCanvasImagesImageIdRouteImport
      parentRoute: typeof ApiCanvasImagesRoute
    }
    '/api/canvas/images/$imageId/inpaint': {
      id: '/api/canvas/images/$imageId/inpaint'
      path: '/inpaint'
      fullPath: '/api/canvas/images/$imageId/inpaint'
      preLoaderRoute: typeof ApiCanvasImagesImageIdInpaintRouteImport
      parentRoute: typeof ApiCanvasImagesImageIdRoute
    }
    '/api/canvas/images/$imageId/generate': {
      id: '/api/canvas/images/$imageId/generate'
      path: '/generate'
      fullPath: '/api/canvas/images/$imageId/generate'
      preLoaderRoute: typeof ApiCanvasImagesImageIdGenerateRouteImport
      parentRoute: typeof ApiCanvasImagesImageIdRoute
    }
  }
}

interface CanvasRouteChildren {
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
  CanvasIndexRoute: CanvasIndexRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiCanvasImagesImageIdRouteChildren {
  ApiCanvasImagesImageIdGenerateRoute: typeof ApiCanvasImagesImageIdGenerateRoute
  ApiCanvasImagesImageIdInpaintRoute: typeof ApiCanvasImagesImageIdInpaintRoute
}

const ApiCanvasImagesImageIdRouteChildren: ApiCanvasImagesImageIdRouteChildren =
  {
    ApiCanvasImagesImageIdGenerateRoute: ApiCanvasImagesImageIdGenerateRoute,
    ApiCanvasImagesImageIdInpaintRoute: ApiCanvasImagesImageIdInpaintRoute,
  }

const ApiCanvasImagesImageIdRouteWithChildren =
  ApiCanvasImagesImageIdRoute._addFileChildren(
    ApiCanvasImagesImageIdRouteChildren,
  )

interface ApiCanvasImagesRouteChildren {
  ApiCanvasImagesImageIdRoute: typeof ApiCanvasImagesImageIdRouteWithChildren
}

const ApiCanvasImagesRouteChildren: ApiCanvasImagesRouteChildren = {
  ApiCanvasImagesImageIdRoute: ApiCanvasImagesImageIdRouteWithChildren,
}

const ApiCanvasImagesRouteWithChildren = ApiCanvasImagesRoute._addFileChildren(
  ApiCanvasImagesRouteChildren,
)

interface ApiCanvasRouteChildren {
  ApiCanvasCanvasIdRoute: typeof ApiCanvasCanvasIdRoute
  ApiCanvasImagesRoute: typeof ApiCanvasImagesRouteWithChildren
}

const ApiCanvasRouteChildren: ApiCanvasRouteChildren = {
  ApiCanvasCanvasIdRoute: ApiCanvasCanvasIdRoute,
  ApiCanvasImagesRoute: ApiCanvasImagesRouteWithChildren,
}

const ApiCanvasRouteWithChildren = ApiCanvasRoute._addFileChildren(
  ApiCanvasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BlocksRoute: BlocksRoute,
  CanvasRoute: CanvasRouteWithChildren,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsersRoute: UsersRoute,
  ApiBlocksRoute: ApiBlocksRoute,
  ApiCanvasRoute: ApiCanvasRouteWithChildren,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatThreadsRoute: ApiChatThreadsRoute,
  ApiContextItemsRoute: ApiContextItemsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUsersRoute: ApiUsersRoute,
  DemoAgentSummaryRoute: DemoAgentSummaryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatAiRoute: ApiChatAiRoute,
  ApiChatGuestRoute: ApiChatGuestRoute,
  ApiChatMutationsRoute: ApiChatMutationsRoute,
  ApiDebugEnvRoute: ApiDebugEnvRoute,
  ApiExplainRenderRoute: ApiExplainRenderRoute,
  ApiExternalContextRoute: ApiExternalContextRoute,
  ApiExternalZergRoute: ApiExternalZergRoute,
  ApiPolarBillingRoute: ApiPolarBillingRoute,
  ApiPolarCheckoutRoute: ApiPolarCheckoutRoute,
  ApiPolarPortalRoute: ApiPolarPortalRoute,
  ApiPolarRefillCheckoutRoute: ApiPolarRefillCheckoutRoute,
  ApiPolarWebhooksRoute: ApiPolarWebhooksRoute,
  ApiScrapeContextRoute: ApiScrapeContextRoute,
  ApiZergCommitSummariesRoute: ApiZergCommitSummariesRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
